[pytest]
testpaths = Test MTS/Test UI Test MTS/Test API
python_files = test_*.py
python_classes = Test*
python_functions = test_*
markers =
    ui: UI тесты
    api: API тесты
addopts = 
    -v
    -s
    --tb=short